apiVersion: v2
name: krakend-operator
description: A Helm chart for krakend-operator responsible for installing and configuring krakend instances into a namespace
sources:
  - https://github.com/nais/krakend/tree/main/charts
type: application
version: 0.1.0
