apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "krakend-operator.fullname" . }}-manager-role
  labels:
  {{- include "krakend-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - krakend.nais.io
  resources:
  - apiendpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - krakend.nais.io
  resources:
  - apiendpoints/finalizers
  verbs:
  - update
- apiGroups:
  - krakend.nais.io
  resources:
  - apiendpoints/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - krakend.nais.io
  resources:
  - krakends
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - krakend.nais.io
  resources:
  - krakends/finalizers
  verbs:
  - update
- apiGroups:
  - krakend.nais.io
  resources:
  - krakends/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "krakend-operator.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: krakend
    app.kubernetes.io/part-of: krakend
  {{- include "krakend-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "krakend-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "krakend-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'