apiVersion: v2
name: krakendinstaller
description: helm chart for krakend used by krakend-operator to install krakend into a namespace
type: application
version: 1.0.0
appVersion: "2.7.0"
dependencies:
  - name: krakend
    version: v0.1.29
    repository: https://helm.equinixmetal.com
