---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.13.0
  name: apiendpoints.krakend.nais.io
spec:
  group: krakend.nais.io
  names:
    kind: ApiEndpoints
    listKind: ApiEndpointsList
    plural: apiendpoints
    singular: apiendpoints
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: ApiEndpoints is the Schema for the apiendpoints API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ApiEndpointsSpec defines the desired state of ApiEndpoints
            properties:
              appName:
                description: AppName is the name of the API, e.g. name of the application
                  or service
                type: string
              auth:
                description: Auth is the common JWT authentication provider used for
                  the endpoints specified in Endpoints
                properties:
                  audience:
                    description: Audience is the list of audiences to validate the
                      JWT against
                    items:
                      type: string
                    type: array
                  cache:
                    description: Cache is whether to cache the JWKs from the auth
                      provider
                    type: boolean
                  debug:
                    description: Debug is whether to enable debug logging for the
                      auth provider
                    type: boolean
                  name:
                    description: Name is the name of the auth provider defined in
                      the Krakend resource, e.g. maskinporten
                    type: string
                  scope:
                    description: Scope is the list of scopes to validate the JWT against
                    items:
                      type: string
                    type: array
                required:
                - name
                type: object
              endpoints:
                description: Endpoints is a list of endpoints that require authentication
                items:
                  description: Endpoint defines the endpoint configuration
                  properties:
                    backendHost:
                      description: BackendHost is the base URL of the backend service
                        and must start with the protocol, i.e. http:// or https://
                      type: string
                    backendPath:
                      description: BackendPath is the path of the backend service
                        and follows the conventions of url_pattern in https://www.krakend.io/docs/backends/#backendupstream-configuration
                      type: string
                    forwardHeaders:
                      description: ForwardHeaders is a list of header names to be
                        forwarded to the backend service, see https://www.krakend.io/docs/endpoints/#input_headers
                      items:
                        type: string
                      type: array
                    method:
                      description: Method is the HTTP method of the endpoint, see
                        https://www.krakend.io/docs/endpoints/#method
                      type: string
                    path:
                      description: Path is exact path of an endpoint in a KrakenD
                        instance and must be unique, see https://www.krakend.io/docs/endpoints/#endpoint
                      type: string
                    queryParams:
                      description: QueryParams is an exact list of query parameter
                        names that are allowed to reach the backend. By default, KrakenD
                        won’t pass any query string to the backend, see https://www.krakend.io/docs/endpoints/#input_query_strings
                      items:
                        type: string
                      type: array
                  type: object
                type: array
              krakend:
                description: Krakend is the name of the Krakend instance in the cluster
                type: string
              openEndpoints:
                description: OpenEndpoints is a list of endpoints that do not require
                  authentication
                items:
                  description: Endpoint defines the endpoint configuration
                  properties:
                    backendHost:
                      description: BackendHost is the base URL of the backend service
                        and must start with the protocol, i.e. http:// or https://
                      type: string
                    backendPath:
                      description: BackendPath is the path of the backend service
                        and follows the conventions of url_pattern in https://www.krakend.io/docs/backends/#backendupstream-configuration
                      type: string
                    forwardHeaders:
                      description: ForwardHeaders is a list of header names to be
                        forwarded to the backend service, see https://www.krakend.io/docs/endpoints/#input_headers
                      items:
                        type: string
                      type: array
                    method:
                      description: Method is the HTTP method of the endpoint, see
                        https://www.krakend.io/docs/endpoints/#method
                      type: string
                    path:
                      description: Path is exact path of an endpoint in a KrakenD
                        instance and must be unique, see https://www.krakend.io/docs/endpoints/#endpoint
                      type: string
                    queryParams:
                      description: QueryParams is an exact list of query parameter
                        names that are allowed to reach the backend. By default, KrakenD
                        won’t pass any query string to the backend, see https://www.krakend.io/docs/endpoints/#input_query_strings
                      items:
                        type: string
                      type: array
                  type: object
                type: array
              rateLimit:
                description: RateLimit is the common rate limit configuration used
                  for the endpoints specified in Endpoints and OpenEndpoints
                properties:
                  capacity:
                    description: 'Capacity is documented here: https://www.krakend.io/docs/endpoints/rate-limit/#configuration'
                    type: integer
                  clientCapacity:
                    description: 'ClientCapacity is documented here: https://www.krakend.io/docs/endpoints/rate-limit/#configuration'
                    type: integer
                  clientMaxRate:
                    description: 'ClientMaxRate is documented here: https://www.krakend.io/docs/endpoints/rate-limit/#configuration'
                    type: integer
                  maxRate:
                    description: 'MaxRate is documented here: https://www.krakend.io/docs/endpoints/rate-limit/#configuration'
                    type: integer
                  strategy:
                    description: 'Strategy is documented here: https://www.krakend.io/docs/endpoints/rate-limit/#configuration'
                    type: string
                required:
                - capacity
                - clientCapacity
                - clientMaxRate
                - maxRate
                - strategy
                type: object
            type: object
          status:
            description: ApiEndpointsStatus defines the observed state of ApiEndpoints
            properties:
              synchronizationHash:
                type: string
              synchronizationTimestamp:
                format: date-time
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
